name: CI/CD Pipeline for Portfolio Application with Docker

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: self-hosted  # This runs on your self-hosted runner (VM)

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional, but recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or token

      # Step 4: Get short commit SHA
      - name: Get short commit SHA
        id: sha
        run: echo "::set-output name=commit_sha::$(git rev-parse --short HEAD)"

      # Step 5: Build the Docker image and tag it with the latest commit SHA
      - name: Build and Push Docker image
        run: |
          # Build the Docker image and tag it with the short commit SHA
          docker build -t rakeshbasnet/rakeshbasnet:${{ steps.sha.outputs.commit_sha }} .
          docker push rakeshbasnet/rakeshbasnet:${{ steps.sha.outputs.commit_sha }}

  deploy:
    needs: build  # This job will run after the build job finishes
    runs-on: self-hosted  # Run this on your self-hosted runner (VM)

    steps:
      # Debug the commit sha.
      - name: Debug commit SHA
        run: echo "Commit SHA; ${{ needs.build.outputs.commit_sha }}"

      # Step 1: Pull the latest Docker image using the commit SHA tag
      - name: Pull Docker image by commit SHA
        run: |
          docker pull rakeshbasnet/rakeshbasnet:${{ needs.build.outputs.commit_sha }}

      # Step 2: Stop and remove any old container
      - name: Stop and remove old container
        run: |
          docker ps -q --filter "name=rakeshbasnet" | xargs -r docker stop | xargs -r docker rm

      # Step 3: Run the latest Docker image with the commit SHA tag
      - name: Run Docker container
        run: |
          docker run -d --name rakeshbasnet -p 80:3000 rakeshbasnet/rakeshbasnet:${{ steps.sha.outputs.commit_sha }}
